### ISSUE TITLE
String in wrong case when creating an instance of MPEGMode

### ISSUE THREAD

**Issue by jvtrigueros** [Sciss/jump3r#3]
On [LameEncoder.java:304](https://github.com/Sciss/jump3r/blob/master/src/main/java/de/sciss/jump3r/lowlevel/LameEncoder.java#L304), the following causes problems:

```java
gfp.mode = Enum.valueOf(MPEGMode.class, chmode2string(mode));
```
Because the return value from `chmod2string` returns a String that's all lowercase which `Enum.value` does not know how to handle.

It's the difference between doing this:
```java
Enum.valueOf(MPEGMode.class, "stereo");
// vs
Enum.valueOf(MPEGMode.class, "STEREO");
```

A super quick and dirty solution would be to append `.toUpperCase()`:
```java
gfp.mode = Enum.valueOf(MPEGMode.class, chmode2string(mode).toUpperCase());
```

A much better solution IMHO would be to encode that in the `chmod2string` method directly:
```java
	private String chmode2string(int chmode) {
                String mode = "auto";
		if (chmode == CHANNEL_MODE_STEREO) {
			mode = "stereo";
		} else if (chmode == CHANNEL_MODE_JOINT_STEREO) {
			mode = "jointstereo";
		} else if (chmode == CHANNEL_MODE_DUAL_CHANNEL) {
			mode = "dual";
		} else if (chmode == CHANNEL_MODE_MONO) {
			mode = "mono";
		} else if (chmode == CHANNEL_MODE_AUTO) {
			mode = "auto";
		}
		return mode;
	}
```

**Comment by Sciss** [comment]
Thanks for the report; I checked in a fix, which is indeed very simple because LameEncoder duplicates the values of the enum for some reason.
