### ISSUE TITLE
Can I only calculate replaygain?

### ISSUE THREAD

**Issue by Xerus2000** [Sciss/jump3r#4]
I would like to integrate ReplayGain calculation into a java project of mine and this library seems to be closest to my goal. Is it possible to just calculate ReplayGain, preferably by a direct call to the library? Can the calculation code be separated and used standalone?

**Comment by Sciss** [comment]
I'm not the original author, so my knowledge of the codebase is limited. If you look into the code, you'll see that `ReplayGain` is the data structure for analysis, and `GainAnalysis` is the class that computes the analysis. `Main` creates a new instance of `GainAnalysis`, puts it into `Lame`, and that then calls `InitGainAnalysis` once, followed `AnalyzeSamples` for the input samples. Finally use `GetTitleGain` to get the result.

**Comment by Xerus2000** [comment]
oh damn that's such a big mess, everything is so heavily intertwined. I just wanna know how to get the samples from an audio file, but I can't seem to find the right method. I am still wondering why there is no simple ReplayGain java lib out there...
